server:
  port: 7777
# our own configuration for the file storage
file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"
spring:
  servlet: # this is for file upload
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  datasource:
    username: postgres
    password: Panha12345
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Mini Project
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # or update
    generate-ddl: true
springdoc:
  swagger-ui:
    path: /

