server:
  port: 7777

file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    username: postgres
    password: roza2023
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e_learning_dev_db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true


